[general]
name = "Swiss Horoscope"

[theme]
primaryColor = "#9333ea"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e1b4b"
tertiaryBackgroundColor = "#312e81"
textColor = "#e2e8f0"
font = "Sans Serif"

[runner]
magicEnabled = true
